name: DRAFT Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_url:
        description: 'GitHub API Release URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release-info.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1

      - name: Fetch release JSON
        id: release-info
        run: |
          mkdir -p assets
          curl -sSL "${{ github.event.inputs.release_url }}" > release.json
          echo "$(jq -r .tag_name release.json)" | tee VERSION
          jq -c '.assets[]' release.json | while read asset; do
            name=$(echo $asset | jq -r .name)
            url=$(echo $asset | jq -r .browser_download_url)
            curl -L -o "assets/$name" "$url"
          done

      - name: Build Darwin arm64
        run: .github/ci-scripts/build.bash \
               -a assets/act_Darwin_arm64.tar.gz \
               -p macosx_arm64 \

      - name: Build Darwin x86_64
        run: .github/ci-scripts/build.bash \
               -a assets/act_Darwin_x86_64.tar.gz \
               -p macosx_x86_64 \

      - name: Build Linux arm64
        run: .github/ci-scripts/build.bash \
               -a assets/act_Linux_arm64.tar.gz \
               -p manylinux_arm64 \

      - name: Build Linux armv6l
        run: .github/ci-scripts/build.bash \
               -a assets/act_Linux_armv6.tar.gz \
               -p manylinux_armv6l \

      - name: Build Linux armv7l
        run: .github/ci-scripts/build.bash \
               -a assets/act_Linux_armv7.tar.gz \
               -p manylinux_armv7l \

      - name: Build Linux i386
        run: .github/ci-scripts/build.bash \
               -a assets/act_Linux_i386.tar.gz \
               -p manylinux_i386 \

      - name: Build Linux riscv64
        run: .github/ci-scripts/build.bash \
               -a assets/act_Linux_riscv64.tar.gz \
               -p manylinux_riscv64 \

      - name: Build Linux x86_64
        run: .github/ci-scripts/build.bash \
               -a assets/act_Linux_x86_64.tar.gz \
               -p manylinux_x86_64 \

      - name: Build Windows arm64
        run: .github/ci-scripts/build.bash \
               -a assets/act_Windows_arm64.zip \
               -p win_arm64 \

      - name: Build Windows armv7
        run: .github/ci-scripts/build.bash \
               -a assets/act_Windows_armv7.zip \
               -p win_armv7l \

      - name: Build Windows 32-bit
        run: .github/ci-scripts/build.bash \
               -a assets/act_Windows_i386.zip \
               -p win32 \

      - name: Build Windows 64-bit
        run: .github/ci-scripts/build.bash \
            -a assets/act_Windows_x86_64.zip \
            -p win_amd64 \

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-wheels
          path: wheels/*.whl
          if-no-files-found: error

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
          - macos-13
          - macos-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: build-wheels
          path: dist

      - name: Install + Test
        run: |
          shopt -s globstar
          pip install --force-reinstall dist/*.whl
          act --version
          act --help
